//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computers()
        {
            this.ComputerHard = new HashSet<ComputerHard>();
            this.ComputersVideo = new HashSet<ComputersVideo>();
            this.OS = new HashSet<OS>();
            this.PhysicalMemory = new HashSet<PhysicalMemory>();
        }
    
        public int id { get; set; }
        public string MacAdress { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<int> MotherBoardId { get; set; }
        public Nullable<int> ProcessorId { get; set; }
        public Nullable<System.DateTime> DateCheck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerHard> ComputerHard { get; set; }
        public virtual MotherBoards MotherBoards { get; set; }
        public virtual Processors Processors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputersVideo> ComputersVideo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS> OS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalMemory> PhysicalMemory { get; set; }
    }
}
