//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardDrives
    {
        public int Id { get; set; }
        public int IdPC { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public Nullable<double> SizeGB { get; set; }
        public Nullable<double> BufferMB { get; set; }
        public Nullable<double> SpeedWriteMBS { get; set; }
        public Nullable<double> SpeedReadMBS { get; set; }
        public string Interface { get; set; }
    
        public virtual Computers Computers { get; set; }
    }
}
