//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemScanner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputersInfoEntities1 : DbContext
    {
        public ComputersInfoEntities1()
            : base("name=ComputersInfoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComputerHard> ComputerHard { get; set; }
        public virtual DbSet<Computers> Computers { get; set; }
        public virtual DbSet<ComputersVideo> ComputersVideo { get; set; }
        public virtual DbSet<HardDrives> HardDrives { get; set; }
        public virtual DbSet<MotherBoards> MotherBoards { get; set; }
        public virtual DbSet<OS> OS { get; set; }
        public virtual DbSet<PhysicalMemory> PhysicalMemory { get; set; }
        public virtual DbSet<Processors> Processors { get; set; }
        public virtual DbSet<VideoControllers> VideoControllers { get; set; }
    }
}
