//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBoards
    {
        public int Id { get; set; }
        public int IdPC { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> SlotsMemory { get; set; }
        public string MemoryType { get; set; }
        public Nullable<double> MaxPhysicalMemoryMB { get; set; }
        public Nullable<int> CanalsMemoryCount { get; set; }
        public Nullable<int> SlotsPCI { get; set; }
        public Nullable<int> SlotsPCIEx1 { get; set; }
        public Nullable<int> SlotsPCIE30x16 { get; set; }
        public Nullable<int> SlotsSata2 { get; set; }
        public Nullable<int> SlotsSata3 { get; set; }
        public Nullable<int> SlotsPS2 { get; set; }
        public Nullable<int> USB20 { get; set; }
        public Nullable<int> USB30 { get; set; }
        public Nullable<bool> VGA { get; set; }
        public Nullable<bool> DVI { get; set; }
        public Nullable<bool> HDMI { get; set; }
        public string EthernetController { get; set; }
        public string AudioController { get; set; }
    
        public virtual Computers Computers { get; set; }
    }
}
