//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processors()
        {
            this.Computers = new HashSet<Computers>();
        }
    
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<double> NumberOfCores { get; set; }
        public Nullable<double> ThreadCount { get; set; }
        public Nullable<double> StartClockSpeed { get; set; }
        public Nullable<double> L1CacheMB { get; set; }
        public Nullable<double> L2CacheMB { get; set; }
        public Nullable<double> L3CacheMB { get; set; }
        public Nullable<double> TechnicalProcess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Computers> Computers { get; set; }
    }
}
