//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processors
    {
        public int Id { get; set; }
        public int IdPC { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> NumberOfCores { get; set; }
        public Nullable<int> ThreadCount { get; set; }
        public Nullable<double> StartClockSpeed { get; set; }
        public Nullable<double> L1CacheMB { get; set; }
        public Nullable<double> L2CacheMB { get; set; }
        public Nullable<double> L3CacheMB { get; set; }
        public Nullable<double> TechnicalProcess { get; set; }
    
        public virtual Computers Computers { get; set; }
    }
}
