//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoControllers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoControllers()
        {
            this.ComputersVideo = new HashSet<ComputersVideo>();
        }
    
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string VideoProcessor { get; set; }
        public Nullable<double> AdapterRAMMB { get; set; }
        public Nullable<double> MaxRefreshRate { get; set; }
        public Nullable<int> CurrentVerticalResolution { get; set; }
        public Nullable<int> CurrentVHorizontalResolution { get; set; }
        public string MemoryType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputersVideo> ComputersVideo { get; set; }
    }
}
